Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "ubuntu/xenial64"
    vm1.vm.network "private_network",ip:"192.168.25.2"
    vm1.vm.provider "virtualbox" do |vb|
	 vb.memory = "2000"
    end
  end		
  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "ubuntu/xenial64"
    vm2.vm.network "private_network",ip:"192.168.25.3"
    vm2.vm.provider "virtualbox" do |vb|
	 vb.memory = "2000"
    end 		
  end
end
